---
- name: Ansible ec2 launch
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    keypair: keypair
    instance_type: t2.micro
    instance_name: test-ec2-instance
    image: ami-0866a3c8686eaeeba
    wait: yes
    group: webserver
    region: us-east-1
  tasks:
  - name: creating ec2 instance
    ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type}}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        wait_timeout: 3
